platform :ios, '8.0'
use_frameworks!


pod 'Reveal-iOS-SDK', :configurations => ['Debug']
pod 'AFNetworking'
pod 'Alamofire', '~> 3.0'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'SnapKit'
pod 'FFLabel'
pod 'FMDB/SQLCipher'
pod 'YYKit'
pod 'SwiftyJSON'
pod 'Kingfisher', '~> 2.0'